package com.liukhtenko.ticket.command;

public class FormParameterName {
    public static final String DEFAULT_VALUE = "\"\"";
    public static final String FORM_PARAM_ADD_EVENT = "addEvent";
    public static final String FORM_PARAM_DELETE_EVENT = "delete event";
    public static final String FORM_PARAM_ADD_TICKET = "addTicket";
    public static final String FORM_PARAM_DELETE_TICKET = "delete ticket";
    public static final String FORM_PARAM_LOGOUT = "logout";
    public static final String FORM_PARAM_TICKETS = "tickets";
    public static final String FORM_PARAM_USER_TICKETS = "userTickets";
    public static final String FORM_PARAM_EVENT_NAME = "eventName";
    public static final String FORM_PARAM_USER = "user";
    public static final String FORM_PARAM_IS_ADMIN= "isAdmin";
    public static final String FORM_PARAM_IS_USER= "isUser";
    public static final String FORM_PARAM_EVENTS= "events";
    public static final String FORM_PARAM_TICKET_OFFICES= "ticketOffices";
    public static final String FORM_PARAM_REMAINING_TICKETS= "remTickets";
    public static final String FORM_PARAM_END= "end";
    public static final String FORM_PARAM_ERROR_PHONE= "errorphone";
    public static final String FORM_PARAM_ERROR_NAME= "errorname";
    public static final String FORM_PARAM_ERROR_SURNAME= "errorsurname";
    public static final String FORM_PARAM_ERROR_FATHER_NAME= "errorFatherName";
    public static final String FORM_PARAM_ERROR_PASSWORD= "errorpassword";
    public static final String FORM_PARAM_ERROR_MAIL= "errormail";
    public static final String FORM_PARAM_TICKET_SIZE= "TicketsSize";
    public static final String FORM_PARAM_PAGE= "page";
    public static final String FORM_PARAM_COUNT_PAGES= "noOfPages";
    public static final String FORM_PARAM_CURRENT_PAGE= "currentPage";
    public static final String FORM_PARAM_LOCALE= "locale";
    public static final String LOCALE_RU= "ru_RU";
    public static final String LOCALE_EN= "en_US";
    public static final String LANGUAGE_RU = "ru";
    public static final String LANGUAGE_EN = "en";
    public static final String MESSAGE_DIGEST= "MD5";
    public static final String POST= "POST";
    public static final String DATE_FORMAT= "yyyy-MM-dd HH:mm:ss";
    public static final String SIMPLE_DATE_FORMAT= "yyyy-MM-dd";
    public static final int HEXADECIMAL_FORMAT= 0xff;
    public static final int HEXADECIMAL_FORMAT_ADD= 0x100;
    public static final int RADIX= 16;
    public static final int ADMIN_ID = 1;
    public static final int FIRST_PAGE = 1;
    public static final int OFFSET = 1;
    public static final int USER_ID = 2;
    public static final int RECORDS_PER_PAGE = 3;
    public static final int GUEST_ID = 0;
}
